apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: familyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      nodeSelector:
        jetson: "true"
      containers:
        - name: piper
          image: familyai/piper:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VOICE
              value: en_US-amy-low
          ports:
            - containerPort: 8600
---
apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: familyai
spec:
  selector:
    app: piper
  ports:
    - name: http
      port: 8600
      targetPort: 8600
  type: ClusterIP
