apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision
  namespace: familyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vision
  template:
    metadata:
      labels:
        app: vision
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        jetson: "true"
      containers:
        - name: vision
          image: familyai/vision:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8300
---
apiVersion: v1
kind: Service
metadata:
  name: vision
  namespace: familyai
spec:
  selector:
    app: vision
  ports:
    - name: http
      port: 8300
      targetPort: 8300
  type: ClusterIP
