apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: familyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      nodeSelector:
        jetson: "true"
      containers:
        - name: web-ui
          image: familyai/web-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GATEWAY_URL
              value: http://gateway.familyai.svc.cluster.local:8080
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: familyai
spec:
  selector:
    app: web-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
