apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: familyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        jetson: "true"
      containers:
        - name: whisper
          image: familyai/whisper:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_NAME
              value: small
          ports:
            - containerPort: 8500
          volumeMounts:
            - name: model-cache
              mountPath: /models/hf-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: familyai
spec:
  selector:
    app: whisper
  ports:
    - name: http
      port: 8500
      targetPort: 8500
  type: ClusterIP
