global:
  scrape_interval: 15s

scrape_configs:
  - job_name: control-plane
    static_configs:
      - targets:
          - control-plane:9000
  - job_name: gateway
    static_configs:
      - targets:
          - gateway:8080
  - job_name: vllm
    static_configs:
      - targets:
          - vllm:8000
  - job_name: whisper
    static_configs:
      - targets:
          - whisper:8500
  - job_name: piper
    static_configs:
      - targets:
          - piper:8600
  - job_name: vision
    static_configs:
      - targets:
          - vision:8300
